force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/Lesson__c.object-meta.xml
<CustomObject>
    <label>Lesson</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lesson Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lessons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lesson__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Lessons</relationshipLabel>
    <relationshipName>Lessons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LessonsController.cls
/**
 * Created by DmytroPinchuk on 21.08.2019.
 */

global with sharing class LessonsController {

    @AuraEnabled
    global static Map<String, String> getLessonsTimes(String ourDate) {
        Date newDate = Date.valueOf(ourDate);
        List<Lesson__c> lessons = [SELECT Id,Name, Date__c, Time__c,Course__r.Name FROM Lesson__c WHERE Date__c = :newDate];
        Map<String, String> courseAndLessonTime = new Map<String, String>();
        List<String> times = new List<String>();
        for (Lesson__c lesson : lessons) {
            Time ourTime = lesson.Time__c;
            Integer ourMinutes = ourTime.minute();
            String minutes ;
            if(ourMinutes < 10){
                minutes = '0' + ourMinutes;
            } else {
                minutes = ourMinutes.format();
            }
            String timeString = ourTime.hour() + ':' + minutes;
            courseAndLessonTime.put((String) lesson.Course__r.Name, timeString);
            times.add(timeString);
        }
        return courseAndLessonTime;
    }
}