force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlot__c/TimeSlot__c.object-meta.xml
<CustomObject>
    <label>TimeSlot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TimeSlot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSlots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlot__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>TimeSlots</relationshipLabel>
    <relationshipName>TimeSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SubjectInfoControllerTest.cls
/**
 * Created by DmytroPinchuk on 26.09.2019.
 */

@IsTest
private class SubjectInfoControllerTest {
    @IsTest
    static void testUrl() {
        String urlString = SubjectInfoController.getUrlsString();
        System.assertEquals(urlString != null, true);
    }
    @IsTest
    static void testSubjectContents() {
        List<Subject__c> subjects = TestDataFactory.insertSubjects(1);
        Test.startTest();
        List<ContentVersion> cv = SubjectInfoController.getSubjectContents(subjects[0]);
        Test.stopTest();
        System.assertEquals(cv.isEmpty(), true);

    }
    @IsTest
    static void testSubjectCourses() {
        List<Subject__c> subjects = TestDataFactory.insertSubjects(1);
        List<TimeSlot__c> timeSlots = TestDataFactory.insertTimeSlots(1,subjects[0].Id);
        List<Course__c> courses = TestDataFactory.insertCourses(1, subjects[0]);
        Test.startTest();
        List<Course__c> coursesList = SubjectInfoController.getSubjectCourses(subjects[0]);
        Test.stopTest();
        System.assertEquals(1, coursesList.size());
    }
}