force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SubjectInfoController.cls
/**
 * Created by DmytroPinchuk on 17.09.2019.
 */

public with sharing class SubjectInfoController {
    @AuraEnabled
    public static String getUrlsString() {
        String networkString = URL.getSalesforceBaseUrl().toExternalForm();
        return networkString;
    }
    @AuraEnabled(cacheable = true)
    public static List<ContentVersion> getSubjectContents(Subject__c subject) {
        ContentDocumentLinkSelector cdlSelector = new ContentDocumentLinkSelector();
        List<ContentDocumentLink> contentDocumentLinks = cdlSelector.selectBySubjectId(subject.Id);
        Set<Id> cdIds = SetUtility.getIds(ContentDocumentLink.ContentDocumentId, contentDocumentLinks);
        ContentVersionSelector cvSelector = new ContentVersionSelector();
        List<ContentVersion> cv = cvSelector.selectByContentDocumentId(cdIds);
        return cv;
    }

    @AuraEnabled(cacheable = true)
    public static List<Course__c> getSubjectCourses(Subject__c subject) {
        CourseSelector courseSelector = new CourseSelector();
        List<Course__c> courses = courseSelector.selectBySubjectId(subject.Id);
        return courses;
    }
}