force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlot__c/TimeSlot__c.object-meta.xml
<CustomObject>
    <label>TimeSlot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TimeSlot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSlots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlot__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>TimeSlots</relationshipLabel>
    <relationshipName>TimeSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MapUtilityTest.cls
/**
 * Created by DmytroPinchuk on 01.09.2019.
 */

@isTest
public with sharing class MapUtilityTest {

    @isTest static void testGroupRecordsByIds() {
        List<Subject__c> subjects = TestDataFactory.insertSubjects(1);
        List<Id> subjectIds = ListUtility.getIds(Subject__c.Id, subjects);
        List<TimeSlot__c> timeSlots = new List<TimeSlot__c>();
        for (Id subId : subjectIds) {
            timeSlots.addAll(TestDataFactory.insertTimeSlots(2, subId));
        }
        Test.startTest();
        Map<Id, List<TimeSlot__c>> timeSlotsBySubjectIds = (Map<Id, List<TimeSlot__c>>)
                MapUtility.groupRecordByIds(TimeSlot__c.Subject__c, timeSlots, Map<Id, List<TimeSlot__c>>.class, List<TimeSlot__c>.class);
        Test.stopTest();

        System.assertEquals(1, timeSlotsBySubjectIds.size());
        System.assertEquals(2, timeSlotsBySubjectIds.get(subjectIds[0]).size());

    }

}