force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/fields/Lesson_Duration__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Duration__c</fullName>
    <label>Lesson Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subject__c/fields/Number_of_Lessons__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Lessons__c</fullName>
    <label>Number of Lessons</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SubjectSelector.cls
/**
 * Created by DmytroPinchuk on 26.09.2019.
 */

public with sharing class SubjectSelector extends fflib_SObjectSelector{
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Subject__c.Lesson_Duration__c,
                Subject__c.Id,
                Subject__c.Number_of_Lessons__c,
                Subject__c.Name
        };
    }
    public Schema.SObjectType getSObjectType() {
        return Subject__c.sObjectType;
    }

    public List<Subject__c> selectSubject() {
        return (List<Subject__c>) Database.query(
                newQueryFactory().
                        toSOQL()

        );
    }
}