force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/fields/Lesson_Duration__c.field-meta.xml
<CustomField>
    <fullName>Lesson_Duration__c</fullName>
    <label>Lesson Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subject__c/fields/Number_of_Lessons__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Lessons__c</fullName>
    <label>Number of Lessons</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SubjectQuerySelector.cls
/**
 * Created by DmytroPinchuk on 09.10.2019.
 */

public with sharing class SubjectQuerySelector extends QueryBuilder{
    public List<Subject__c> getSubjectsByName(String subjectName) {
        return (List<Subject__c>) new QueryBuilder(Subject__c.class)
                .addField('Id')
                .addField('Name')
                .addField('Number_of_Lessons__c')
                .addField('Lesson_Duration__c')
                .addConditions()
                .add(new QueryBuilder.CompareCondition('Name').eq(subjectName))
                .endConditions()
                .toList();
    }
}