force-app/main/default/objects/Lead/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>ApprovalStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subject__c/Subject__c.object-meta.xml
<CustomObject>
    <label>Subject</label>
    <nameField>
        <label>Subject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subject__c/fields/Number_of_Lessons__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Lessons__c</fullName>
    <label>Number of Lessons</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TimeSlot__c/TimeSlot__c.object-meta.xml
<CustomObject>
    <label>TimeSlot</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>TimeSlot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSlots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSlot__c/fields/DayOfWeek__c.field-meta.xml
<CustomField>
    <fullName>DayOfWeek__c</fullName>
    <label>DayOfWeek</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TimeSlot__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <referenceTo>Subject__c</referenceTo>
    <relationshipLabel>TimeSlots</relationshipLabel>
    <relationshipName>TimeSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/Utilities/TestDataFactory.cls
/**
 * Created by DmytroPinchuk on 21.08.2019.
 */

public with sharing class TestDataFactory {

    public static List<Subject__c> insertSubjects(Integer numberOfSubjects) {
        List<Subject__c> subjects = new List<Subject__c>();
        for (Integer i = 1; i <= numberOfSubjects; i++) {
            subjects.add(new Subject__c(Name = 'SomeSubject' + i, Number_of_Lessons__c = i));
        }
        insert subjects;
        return subjects;
    }

    public static List<TimeSlot__c> insertTimeSlots(Integer numberOfTimeSlots, Id subjectId) {
        List<TimeSlot__c> timeSlots = new List<TimeSlot__c>();
        for (Integer i = 1; i <= numberOfTimeSlots; i++) {
            timeSlots.add(new TimeSlot__c(DayOfWeek__c = 'Monday',
                    Time__c = Time.newInstance(09 + i, 00, 00, 00), Subject__c = subjectId));
        }
        insert timeSlots;
        return timeSlots;
    }

    public static List<Lead> insertLeads(Integer numberOfLeads) {
        List<Lead> leads = new List<Lead>();
        for (Integer i = 1; i <= numberOfLeads; i++) {
            leads.add(new Lead(FirstName = 'TestName' + i, LastName = 'LastTestName' + i,
                    Company = 'TestCompanyName' + i, Status = 'Open - Not Contacted', Email = 'somtestemail'+ i + '@gmail.com'));
        }
        insert leads;
        return leads;
    }
    public static List<Lead> formPotentialLeads(Integer numberOfLeads) {
        List<Lead> leads = new List<Lead>();
        for (Integer i = 1; i <= numberOfLeads; i++) {
            leads.add(new Lead(FirstName = 'TestName' + i, LastName = 'LastTestName' + i,
                    Company = 'TestCompanyName' + i,Email = 'somtestemail'+ i + '@gmail.com'));
        }
        return leads;
    }
    public static List<Lead> updateToApproval(List<Lead> leads){
        List<Lead> approvedLeads = new List<Lead>();
        for(Lead lead : leads){
            lead.ApprovalStatus__c = 'Approved';
            approvedLeads.add(lead);
        }
        update approvedLeads;
        return approvedLeads;
    }
    public static List<Lead> updateToRejected(List<Lead> leads){
        List<Lead> rejectedLeads = new List<Lead>();
        for(Lead lead : leads){
            lead.ApprovalStatus__c = 'Rejected';
            rejectedLeads.add(lead);
        }
        update rejectedLeads;
        return rejectedLeads;
    }
}